PennyPilot-Tech-Residency-37/pennypilot

- src/components/HomeDashboard.tsx
- src/custom.d.ts
- src/types/images.d.ts
> Home dashboard

- src/components/BudgetPlanner.tsx
> Budget planner

- package-lock.json
- package.json
- src/components/Navbar.tsx
- src/components/PilotAvatar.tsx
- src/types.d.ts
Added PilotAvatar.tsx to handle our Avatar.
> Pilot avatar

- src/components/HomeDashboard.tsx
Added firebaseConfig to HomeDashboard.tsx.
> Added firebaseConfig to HomeDashboard.tsx

- README.md
I added an "Authors" section to the README.md file. Underneath the heading, I added my name as a bullet point.
> Added Authors Section and Name

- .gitignore
- backend/util.py
- requirements.txt
Added util.py file for login confirmation (will finish other login things later), added python-jose to requirements.txt, added root_password.py to gitignore (hopefully that works)
> Login confirmation

- src/components/LoginModal.tsx
added confirm password field to sign up, added hide/view toggle icon for password fields
> added confirm password  to sign up, hide/view toggle icon to password

- __mocks__/firebaseConfig.ts
- eslint.config.js
- jest.config.cjs
- jest.setup.ts
- package-lock.json
- package.json
- src/components/LoginModal.test.tsx
- tsconfig.json
i added a test file to verify that the LoginModal is working correctly. I mocked firebase authentication and an account creation.
> set up a test for LoginModal

- backend/database_link.py
This pull request should go to the right branch
> Remove database_link.py again

- backend/models.py
I have fixed the tax info error in the backend
> fixed tax info error

- package-lock.json
- package.json
- src/components/BudgetGuide.tsx
- src/components/BudgetPlanner.tsx
the budget guide is the step navigation experience that the user will see before their actual built-out budget. The step navigation has 5 steps: income, expenses, savings, summary, and confirmation (this step has confetti).
> created the budget guide

- backend/models.py
- backend/routes/budget.py
- backend/routes/expenses.py
- backend/routes/income.py
- backend/routes/savings.py
- backend/schemas.py
This should probably be checked over before being approved. I am not confident in my own work.
> Add tables for income, expenses, savings, and budget

- .firebaserc
- Security  Folder/iam-rbac-model.md
- Security  Folder/logging-monitoring-setup.md
- Security  Folder/security-infrastructure-guide.md
- firebase.json
- firestore.indexes.json
- firestore.rules
- functions/.gitignore
- functions/index.js
- functions/package-lock.json
- functions/package.json
- package-lock.json
pushing this code on behalf of Kevin. I'll have him review this and merge the pull request.
> Sprint 1 includes IAM, RBAC, infra, logging, configs, and diagrams.

- src/components/LoginModal.tsx
- src/components/Navbar.tsx
Updated Navbar.tsx and Login Modal if user clicks a nav link it will trigger login modal.
> Navbar modal update

- src/components/BudgetGroup.tsx
- src/components/BudgetPlanner.tsx
- src/components/BudgetSummaryChart.tsx
Enhance the budgeting application's layout by updating pilot image positions, button and accordion styling, and grid layout, while implementing responsive design to ensure usability and visual balance across mobile, tablet, and desktop devices.
> Budget page layout and responsiveness

- src/components/BudgetSummaryChart.tsx
Moved budget list links below Create New Budget button and above pie chart on BudgetSummaryChart.tsx.
> Moved Budget List below Create New Budget Button

- src/components/BudgetPlanner.tsx
- src/components/Dashboard.tsx
Summary
- Budgets are now persisted in Firestore, so user data is retained across navigation and reloads.
- Added a summary section and mini pie charts for each budget on the Budget page and Dashboard.
- Improved type safety and fixed TypeScript errors in budget summary helpers.
Details
- Integrated Firestore CRUD for budgets in BudgetPlanner.tsx.
- Dashboard now displays a quick summary of budgets and a pie chart for each.
- Refactored state management to fetch and update budgets in real time.
- Fixed linter/type errors for chart helpers.
Motivation
- Previously, budget data was lost when navigating away from the page.
- This change ensures a consistent, persistent user experience, similar to the TaxPrep page.
> Connected Budgets and Budget Charts to Dashboard

- backend/app.py
- backend/key_utils.py
- backend/plaid_client_config.py
- backend/routes/create_link_token.py
Added key hashing and salting and implemented them in files
> Implement key hashing security features

- backend/key_utils.py
a function in the salting and hashing logic was throwing an error so I fixed it
> fixed validate key function throwing error

- src/components/Dashboard.tsx
- src/components/LandingPage.tsx
Dashboard UI Enhancements
Changes Made
- Added cloud background with PennyPilot-cloud-background.jpg
- Implemented flying plane animation that triggers on user inactivity
- Added spinning PennyPilot logo as loading indicator
- Adjusted pilot message bubble positioning to the right
- Optimized spacing around pilot avatar
- Changed budget ordering to display oldest first
UI Improvements
- Enhanced visual appeal with animated background elements
- Improved loading states with branded spinning logo
- Better spacing and layout for pilot avatar and message
- More intuitive budget display order (chronological)
- Added Framer Motion for plane animation
- Implemented user inactivity detection
- Adjusted z-index layering for proper visual hierarchy
- Modified Firestore query to …
> Added cloud background and plane to Dashboard.tsx

- src/components/Navbar.tsx
Navbar UI Improvements
Changes Made
- Made logo and PennyPilot text clickable, linking to Dashboard for logged-in users and Home for logged-out users
- Added hover effect (opacity change) to indicate clickability
- Maintained existing logo spin animation on click
- Added spacing between PennyPilot title and user greeting
UI Enhancements
- Improved navigation UX by making the brand elements clickable
- Enhanced visual hierarchy with better spacing
- Maintained consistent behavior with other navigation elements
- Preserved responsive design across all screen sizes
- Wrapped logo and title in a clickable container
- Added onClick handler with conditional routing based on auth state
- Integrated with existing navigation and login modal logic
- Added margin spacing using …
> Navbar edits

- src/components/Navbar.tsx
Navbar UI Enhancement: Gradient, Shadows, and Interactive Elements
Overview
Comprehensive enhancement of the Navbar's visual design and interactivity, creating a more premium and polished user experience.
Changes Made
Background and Structure
- Implemented a stronger three-color gradient background:
- Deep blue (`#0d47a1`) to medium blue (`#1565c0`) to bright blue (`#2196f3`)
- Adjusted color stop positions for optimal visual flow
- Enhanced shadow effects:
- Added dual-layer shadow for depth
- Primary shadow: 20px spread with 15% opacity
- Secondary shadow: 10px spread with 10% opacity
Navigation Links
- Refined hover effects:
- White underline animation that expands from center
- Gold text color (`#ffd700`) on hover
- Subtle elevation effect (1px upward movement)
- Smooth transitions …
> Navbar UI improvements

- src/components/Dashboard.tsx
- src/components/LandingPage.tsx
- src/components/PilotAvatar.tsx
Optimized the spacing and layout of the pilot message and navigation elements to create a more compact and visually balanced interface.
Spacing Adjustments
- Reduced gap between elements from `gap: 3` to `gap: 2` for more compact layout
- Adjusted pilot message positioning:
- Changed message bubble top position from `-120px` to `-80px`
- Maintained consistent spacing across LandingPage and Dashboard
- Refined padding and margins:
- Reduced top padding from `pt: 4` to `pt: 2`
- Kept bottom margin at `mb: -5` for proper content flow
Layout Improvements
- Maintained consistent spacing above pilot section
- Optimized vertical rhythm between components
- Preserved responsive behavior across screen sizes
- Modified spacing in both LandingPage.tsx and Dashboard.tsx
- Updated …
> Refined Spacing in LandingPage and Dashboard

- .firebaserc
- package-lock.json
- package.json
- src/components/TaxPrep.tsx
Added CSV Export for Tax Deductible Expenses
Description
Added functionality to export tax deductible expenses to CSV format, allowing users to easily download and share their expense records.
Changes
- Implemented CSV export functionality in the TaxPrep component
- Added export button with FileDownload icon
- Included proper error handling for empty expense lists
- Formatted CSV output with headers: Date, Category, Amount, Notes
- Added proper escaping for special characters in notes field
- CSV generation handles:
- Date formatting using `toLocaleDateString()`
- Proper escaping of quotes in notes using double-quote escaping
- Automatic file naming with current date: `deductible-expenses-YYYY-MM-DD.csv`
- Export button is disabled when no expenses are available
- Uses …
> Tax prep export capability

- src/components/TaxPrep.tsx
Added Filtering and Sorting to Tax Deductible Expenses Table
Description
Enhanced the TaxPrep component by adding filtering and sorting capabilities to the "Logged Expenses" table. Users can now filter expenses by category and sort by amount, date, or category, making it easier to analyze and manage their tax-deductible expenses.
Changes
- Added category filter dropdown with all predefined categories
- Implemented sortable columns for Amount, Category, and Date
- Added visual indicators for active sort column and direction
- Enhanced empty state messaging to reflect active filters
- Maintained existing styling and animations for consistency
- Added new state management for:
- Sort field (deductibleAmount, createdAt, category)
- Sort order (ascending/descending)
- …
> Added Filtering and Sorting to Tax Deductible Expenses Table

- .env.example
- backend/plaid_client_config.py
- package-lock.json
- package.json
- src/components/BudgetPlanner.tsx
installed react-plaid-link, added button to budget planner file that will allow user to connect their bank account (simulated through plaid api) and provide the app with financial data.
> set foundation for plaid frontend comms

- src/components/Dashboard.tsx
- src/components/PilotAvatar.tsx
- src/components/TaxPrep.tsx
Tax Prep UI Improvements
Changes Made
**Pie Chart Enhancements**
- Adjusted pie chart positioning and sizing for better visibility
- Changed font weight of pie chart labels from bold to normal (700 → 400)
- Centered "Expenses by Category" heading
- Improved legend positioning and spacing
- Adjusted chart container dimensions for better layout
- Modified `renderPieLabel` function to use normal font weight
- Updated Typography component styling with `textAlign: 'center'`
- Adjusted ResponsiveContainer and Box component dimensions
- Fine-tuned legend positioning with updated padding and bottom margin
Visual Improvements
- Better vertical alignment of chart elements
- More balanced spacing between chart components
- Improved overall readability with normal font weight for …
> Tax Prep UI Improvements

- backend/app.py
- backend/base.py
- backend/config.py
- backend/init_keys_table.py
- backend/key_utils.py
- backend/routes/create_link_token.py
- backend/routes/exchange_token.py
- backend/store_dev_key.py
- src/components/BudgetPlanner.tsx
- vite.config.js
set up plaid link token retrieval, adjusted vite config proxy to successfully connect frontend and backend across ports, user can now connect their bank account to the app (simulated through plaid api) with the newly created "Connect Bank Account" button, wrote up logic for "Connect Bank Account" button that launches the plaid link UI
> connected plaid to frontend using axios

- src/app.tsx
- src/components/Footer.tsx
- src/components/LandingPage.tsx
**New Footer Component**
**Summary**
- This PR introduces a new, modern footer for the application, designed to improve navigation, branding, and team visibility.
**Key Features & Changes**
**Branding & Navigation**
- Added the PennyPilot logo and name, both linking to the dashboard, and visually raised for emphasis.
- Included a tagline: “Navigate Your Financial Future.”
- Quick Links section for easy access to Budget Planner, Tax Prep, and Goals pages, with gold color on hover and no underline.
**About Us**
- Added a concise About Us section with a link to Coding Temple (bold and gold on hover).
- Section width reduced for a cleaner, more focused look.
**Team Section**
- Listed all team members (Algorithm Alliance) with their roles (Frontend, Backend, Cybersecurity).
- Each name links …
> New Footer Component

- src/components/BudgetPlanner.tsx
**BudgetPlanner UI/UX Enhancements**
**Summary of Changes:**
- **Bank Connection Card:**
- Reduced card size for a more compact appearance.
- Ensured the entire bank image is visible within the card, with object-fit: contain and a lower opacity for subtlety.
- Adjusted card hover effect to only increase the shadow (no lift/translate for a cleaner look).
- **Connect Your Bank Account Button:**
- Improved button styling for better interactivity and accessibility.
- On hover, the button background now becomes a slightly darker gold (#e6ac00).
- On click (active), the button background darkens further (#c49000) and the shadow is reduced for a tactile effect.
- Removed the vertical movement on click for a more stable feel.
- **General Styling:**
- Fine-tuned spacing, padding, and sizing for a …
> BudgetPlanner UI/UX Enhancements

- src/components/LoginModal.tsx
**Redirect to Dashboard After Login/Sign Up**
**Summary**
- Updated the LoginModal component so that after a successful login or sign up, the user is automatically redirected to the /dashboard route.
- This applies to both the login and sign up flows, ensuring a seamless onboarding experience.
- Removed conditional navigation logic based on intendedPath—all successful authentications now go directly to the dashboard.
**Why:**
This change streamlines the user experience by taking users straight to their dashboard after authentication, reducing friction and making the app more intuitive.
> Redirect to Dashboard After Login/Sign Up

- src/components/LandingPage.tsx
Worked out bugs on TaxPrep button on Landing Page.
> Tax prep button

- src/components/Dashboard.tsx
**Dashboard Goals Card UI & Data Improvements**
**Summary**
- This PR improves the user experience and accuracy of the Financial Goals card on the Dashboard. It ensures that user-created goals and badges are displayed correctly, and that the progress bar chart accurately reflects the user’s savings progress. The visual layout is also refined for consistency and clarity.
- Key Changes
**Goals List:**
- The goals list is now a fixed-height, scrollable list (like the budget card), allowing users to scroll through all their goals without overwhelming the card space.
**Progress Bar Chart:**
- The bar chart for each goal now accurately calculates the “saved” amount based on the number of completed steps and the goal’s frequency and date range, matching the logic used in the Goals page.
- The …
> Dashboard Goals Card UI & Data Improvements

- backend/routes/budget.py
- backend/routes/expenses.py
- backend/routes/goal.py
- backend/routes/home.py
- backend/routes/income.py
- backend/routes/linked_account.py
- backend/routes/savings.py
- backend/routes/tax_info.py
- backend/routes/transaction.py
- backend/routes/user.py
Alex wanted the routes back so I'm re-adding them from my archived files
> Re-add routes

- src/components/BudgetPlanner.tsx
- src/components/Dashboard.tsx
- src/components/TaxPrep.tsx
**Persist All User Data in LocalStorage (Budget, Goals, Tax Prep, Dashboard)**
**Summary**
- This PR ensures that all user-created data (budgets, goals, tax prep/expenses) is stored and loaded from localStorage—not Firestore—so that user data persists across logouts, reloads, and app updates. This matches the robust persistence pattern used in the Goals page and now applies it to BudgetPlanner and TaxPrep as well.
**Key Changes**
**BudgetPlanner**
- Budgets and bank accounts are initialized from localStorage on first render.
- All changes (add, edit, delete) are saved to localStorage immediately.
- No Firestore logic for budgets or accounts.
- UI updates instantly and persists across reloads/logouts.
**TaxPrep**
- Deductible expenses are initialized from localStorage synchronously (on …
> Persist All User Data in LocalStorage (Budget, Goals, Tax Prep)

- src/components/Budget.css
- src/components/BudgetGroup.tsx
- src/components/BudgetPlanner.tsx
- Redesigned budget item layout with two-line display for better readability
- Added progress bar and difference display in a dedicated second line
- Improved spacing and alignment of budget items
- Enhanced tooltips with clearer descriptions
- Adjusted column widths for better content fit
- Made input fields more compact with smaller font sizes
- Added visual separation between items with subtle background colors
- Refactored table structure to use nested Box components for better layout control
- Optimized progress bar display with centered alignment
- Improved responsive behavior with percentage-based widths
- Enhanced typography with consistent font sizes
- Added color coding for positive/negative differences
- Clearer visual hierarchy with separated main and secondary information
- …
> BudgetGroup UI Improvements

- .github/workflows/deploy.yml
**GitHub Actions CI Workflow: Build & Test for Backend and Frontend**
**Summary**
- Added/Updated .github/workflows/deploy.yml to automate CI for both backend and frontend.
**Backend:**
- Sets up a PostgreSQL service for tests.
- Installs Python dependencies and runs backend tests with pytest.
**Frontend:**
- Installs Node.js dependencies and builds the frontend with environment variables from GitHub Secrets.
**Details**
- The workflow runs on every push and pull request to the main branch.
- Backend and frontend are tested/built in parallel jobs.
- No deployment to EC2 is performed yet—this workflow is for build and test only.
- Environment variables and secrets are securely managed via GitHub Actions secrets.
**Next Steps**
- Once the EC2 instance is ready, a deployment job can be added …
> GitHub Actions CI Workflow: Build & Test for Backend and Frontend

- src/app.tsx
- src/components/BudgetPlanner.tsx
- src/components/BudgetSummaryChart.tsx
- src/components/Dashboard.tsx
**Budget Persistence & UI Improvements**
**Summary**
- Improves the reliability and user experience of the Budget Planner by ensuring all budget data is robustly persisted in localStorage and by refining the UI for budget management.
**Key Changes**
- **Removed Firestore Sync:**
- Eliminated the Firestore onSnapshot listener for budgets.
- Now, all budget data is stored and managed exclusively in localStorage, ensuring persistence across reloads, logouts, and app updates.
- **Real-Time Sync Across Tabs:**
- Added a localStorage event listener to keep budgets and the current budget in sync across multiple browser tabs in real time.
- **UI/UX Enhancements:**
- The "Create a New Budget" button is now smaller and has a max width of 250px for a more compact appearance.
- The budget list and …
> Budget Persistence & UI Improvements

- src/components/BudgetSummaryChart.tsx
Edited max height of create new budget button.
> Changed max height of new budget button

- backend/app.py
- backend/routes/create_link_token.py
- backend/routes/linked_account.py
- backend/routes/plaid_routes.py
- backend/routes/transaction.py
- src/components/BudgetGroup.tsx
- src/components/BudgetPlanner.tsx
- src/utils/categorizeTransactions.ts
- readded routes backend successfully configured them
- refactored backend code to include transactions product from plaid api
- updated state management in Budget page to position buttons and remove the bank image once the client has connected their bank account
> successfully fetched api data to convert to budget table and chart

- src/components/BudgetGroup.tsx
- src/components/BudgetGuide.tsx
- src/components/BudgetPlanner.tsx
- src/components/BudgetSummaryChart.tsx
- src/components/Dashboard.tsx
- src/components/Goals.tsx
- src/components/LoginModal.tsx
- src/components/TaxPrep.tsx
- src/context/auth.tsx
- src/types/types.ts
**Pull Request: UI/UX Improvements for Budget Planner**
**Summary**
- This PR introduces a series of UI/UX improvements and bug fixes to the budgeting application, focusing on compactness, clarity, and a more modern, user-friendly experience. The changes are inspired by YNAB and user feedback.
**Key Changes**
1. Budget Creation Button Logic
The "Create a New Budget" button at the top of the planner is now only shown if the user has no budgets.
If the user has budgets, the button is only visible in the BudgetSummaryChart section.
2. Section Spacing and Layout
The "Connect Bank Account" button and connected accounts section have been moved below the budget table/charts and above the backup/restore controls for a more logical flow.
Vertical spacing (mt/mb) above the budget table, charts, and …
> Deleted code restore

- backend/models.py
update in backend/models.py. The db.create.all() now only runs in development. I needed to change this to deploy the app.
PLEASE READ:
contact me for the new variable value that needs to be added in the .env file
> Backend models

- package-lock.json
- package.json
- src/components/BudgetGroup.tsx
- src/components/Dashboard.tsx
- src/components/TaxPrep.tsx
**UI/UX Improvements & Export Features for Tax Prep and Dashboard**
**Summary**
This PR introduces a series of UI/UX improvements and new export features to the Tax Prep and Dashboard pages, focusing on compactness, consistency, and enhanced data export options.
**Key Changes**
**Tax Prep Page**
- **Export Features**
- Added "Export Word" and "Export PDF" buttons alongside "Export CSV" for deductible expenses.
- All export buttons are now vertically stacked, compact, and include a download icon.
- Word export uses the docx library; PDF export uses jsPDF and jspdf-autotable.
- **Card & Section Compactness**
- Reduced padding on all <Card> components for a more compact look.
- Tightened vertical spacing (mb, mt) on headings and sections inside cards.
- Reduced spacing in the "Add Deductible …
> UI/UX Improvements & Export Features for Tax Prep and Dashboard

- .github/workflows/deploy.yml
Ensured proper job sequencing using needs: so jobs run in the correct order
Enabled automatic deployment on every push to the main branch
Corrected the backend dependency installation to use requirements.txt from the root directory
Added a conditional check to skip backend tests if backend/tests folder is missing
Corrected frontend job paths to reflect that the React app is built from the root, not a frontend/ folder
Built the frontend using npm ci for fast, clean, and reproducible builds
Created and securely used a new SSH key pair for deployment via GitHub Actions
Added secrets to GitHub (e.g., EC2_HOST, EC2_USER, EC2_SSH_KEY, and optionally ENV_FILE)
SSHed into the EC2 instance during deploy to pull latest code from GitHub
Rebuilt the React frontend on the EC2 instance using npm run …
> deploy.yml now deploys via ec2 instance

- src/components/BudgetGroup.tsx
- src/components/BudgetPlanner.tsx
- src/components/Dashboard.tsx
This PR implements several UI/UX improvements to the budget table, focusing on making the interface more compact, modern, and visually clean.
- Reduced the height of section headers (Income, Expenses, Savings) from 18px to 16px
- Minimized padding around section headers to 4px
- Removed extra spacing in expanded state
- Aligned header content vertically for better visual balance
- Removed all bottom borders from table rows and cells
- Eliminated underlines from all input fields (name, budgeted amount, activity)
- Maintained hover states for better row interaction feedback
- Kept consistent 18px row height for optimal readability
- Removed all divider lines between rows
- Eliminated default Material-UI input field underlines
- Maintained hover effects for better user interaction feedback
- …
> Budget UI/UX

- src/components/TaxPrep.tsx
- Fixed inconsistent indentation throughout the TaxPrep component
- Updated heading structure in the summary section
- Improved readability of nested JSX elements
- Standardized spacing for component props
- Aligned closing tags properly
- Fixed indentation in conditional rendering blocks
- Improved table structure indentation
- Aligned Material-UI components consistently
- Maintained 2-space indentation for nested elements following React/TypeScript best practices
- Updated heading structure:
- Changed "Total Tax Deductions:" to be more prominent
- Improved typography hierarchy in the summary section
- Fixed indentation in the following sections:
- Summary Cards section
- Export buttons group
- Pie chart component
- Expenses table structure
- Form controls and grid layout
- Conditional …
> Fix Indentation and Update Heading in TaxPrep Component

- package-lock.json
- package.json
- src/components/EditGoalModal.tsx
- src/components/GoalList.tsx
- src/components/Goals.tsx
- src/components/GoalsPath.tsx
- src/components/GoalsToolKit.css
- src/components/GoalsToolKit.tsx
- visual progression of goal with new circular progress bar
- synced up to goal path
- goal settings button so user can edit and save changes to their goal
> created new component GoalsToolKit to manage goals and subgoals
